version: '3'
services:
<<<<<<< HEAD
  
=======
  nginx:
    build: ./nginx
    depends_on:
      - backend
    ports:
      - 80:80

>>>>>>> 3147c996ea1aec30312398d422c19619bbe1d153
  # redis:
  #   image: redis
  #   ports:
  #     - 6379:6379
  
  frontend:
    image: frontend 
  
  managementInterface:
<<<<<<< HEAD
    image: managementinterface
=======
    image: managementInterface
>>>>>>> 3147c996ea1aec30312398d422c19619bbe1d153
  
  backend:
    image: backend
    ports:
      - 3000:3000
  

